title: open-atmos-krk team at AGH University of Krakow
url: http://open-atmos-krk.github.io

exclude: [bibble, README.md, Makefile, screenshot.png, blog]

# colorize code snippets with the pygments module
highlighter: pygments

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty (@<a href="https://zfs.agh.edu.pl/en">zfs.agh.edu.pl</a>)
  - key: grad
    name: Graduate Students (@<a href="https://www.agh.edu.pl/en">agh.edu.pl</a>)
  - key: ugrad
    name: Undergraduate Students (@<a href="https://fis.agh.edu.pl/en">fis.agh.edu.pl</a>)
  - key: alum
    name: Alumni (@<a href="https://agh.edu.pl/en">agh.edu.pl</a> &amp; @<a href="https://www.uj.edu.pl/en">uj.edu.pl</a>)

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      permalink: none

# Navigation bar links.
navigation:
  - title: Team
    link: /
  - title: News
    link: /news.html
  - title: Projects
    link: /projects.html
  - title: Journal Club
    link: /journal_club.html
  - title: Mailing List
    link: /mailing_list.html
  - title: Publications
    link: /publications.html
