title: open-atmos-krk team at AGH University of Krakow
url: http://open-atmos-krk.github.io

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty (@<a href="https://zfs.agh.edu.pl/en">zfs.agh.edu.pl</a>)
  - key: grad
    name: Graduate Students (@<a href="https://www.agh.edu.pl/en">agh.edu.pl</a>)
  - key: ugrad
    name: Undergraduate Students (@<a href="https://fis.agh.edu.pl/en">fis.agh.edu.pl</a>)
  - key: alum
    name: Alumni (@<a href="https://agh.edu.pl/en">agh.edu.pl</a> &amp; @<a href="https://www.uj.edu.pl/en">uj.edu.pl</a>)

# Number of news stories on the front page.
front_page_news: 10

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Team
    link: /
  - title: News
    link: /news.html
  - title: Projects
    link: /projects.html
  - title: Journal Club
    link: /journal_club.html
  - title: Publications
    link: /publications.html
